### ISSUE TITLE
홈화면 & 서버 연동 version.1

### ISSUE THREAD

**Issue by kimmincheol-kor** [yjosp95/Project3#3]
데이터베이스로 부터 상품 목록을 불러와 리스트화 하는 것 까지 구현하겠습니다.

이후 로그인, 상품 조회, 검색, 고객센터 등 다른 페이지를 연결하는 작업 업데이트 필요합니다.

**Comment by hongjinhyeok** [comment]
확인했습니다!

**Comment by yjosp95** [comment]
네 알겠습니다
