### ISSUE TITLE
1. 자체 관리 로그인 구현

### ISSUE THREAD

**Issue by Jeongyonghoon** [yjosp95/Project3#6]
(1)개발자가 자체적으로 관리하는 로그인 구현

(2)쿠키를 통해 사용자 정보를 다른페이지에 전달

**Comment by Jeongyonghoon** [comment]
자체 관리 로그인으로 login view페이지와 Post를 추가하여 DB에 접근 후 
아이디와 비밀번호 유무 확인까지 되도록 DB연결했습니다. 
Pull request와 branch확인해주세요!

**Comment by yjosp95** [comment]
코드 확인했고 다른 팀원들 확인하면 Merge 진행하겠습니다.
